package com.kevin.hannibai;

/**
 * Created by zhouwenkai on 2017/8/13.
 */

final class Utils {

    static <T> void validatePreferenceInterface(Class<T> preference) {
        if (!preference.isInterface()) {
            throw new IllegalArgumentException("Preference declarations must be interfaces.");
        }

        if (preference.getInterfaces().length > 0) {
            throw new IllegalArgumentException("Preference interfaces must not extend other interfaces.");
        }

        if (!preference.getSimpleName().endsWith("Handle")) {
            throw new IllegalArgumentException("Preference must be generated by Hannibai.");
        }
    }

    static <T> T checkNotNull(T object, String message) {
        if (object == null) {
            throw new NullPointerException(message);
        }
        return object;
    }
}
