/*
 * Copyright (c) 2017 Kevin zhou
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.kevin.hannibai.compiler;

/**
 * Created by zhouwenkai on 2017/8/12.
 */

public class Constants {
    public static final String CLASS_JAVA_DOC = "Generated by Hannibai. Do not edit it!\n";

    public static final String GET = "get";
    public static final String CONTAINS = "contains";
    public static final String SET = "set";
    public static final String REMOVE = "remove";
    public static final String REMOVE_ALL = "removeAll";

    public static final String PACKAGE_NAME = "com.kevin.hannibai";
    public static final String DOT = ".";
    public static final String HANNIBAI = "Hannibai";
    public static final String REAL_HANNIBAI = "RealHannibai";
    public static final String IHANDLE = "IHandle";
    public static final String HANDLE_SUFFIX = "Handle";
    public static final String HANDLE_IMPL_SUFFIX = "HandleImpl";

    public static final String CONTAINS_METHOD_JAVA_DOC = "Checks whether the %s contains in preference. \n\nReturns true if the preference exists in the preferences and has not expired, otherwise false.\n";
    public static final String GET_METHOD_JAVA_DOC = "Retrieve the %s from the preferences. \n\n@return Returns the preference value if it exists, or defValue.\n";
    public static final String PUT_METHOD_JAVA_DOC = "Set the %s value to the preferences. \n\n@param %s The new value for the preference.\n";
    public static final String REMOVE_METHOD_JAVA_DOC = "Remove the %s in the preferences. \n\n@return Whether remove success.\n";
    public static final String REMOVE_ALL_METHOD_JAVA_DOC = "Remove all preference in the preferences. \n\n@return Whether remove success.\n";

    public static final String HANNIBAI_ANNOTATION_TYPE = "com.kevin.hannibai.annotation.SharePreference";
}
